version: '3.1'

services:
  # refs: https://verdaccio.org/docs/docker/
  verdaccio:
    image: verdaccio/verdaccio
    container_name: 'verdaccio_htpasswd_v5'
    networks:
      - verdaccio-network
    environment:
      # - VERDACCIO_PUBLIC_URL=https://example.com/
      - VERDACCIO_PORT=4873
      - DEBUG=verdaccio:*
    ports:
      - '4873:4873'
    volumes:
      - './verdaccio/storage:/verdaccio/storage'
      - './verdaccio/conf:/verdaccio/conf'

  ## refs: https://github.com/louislam/uptime-kuma
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: 'uptime-kuma'
    ports:
      - '3001:3001'
    volumes:
      - './uptime-kuma:/app/data'

networks:
  verdaccio-network:
    driver: bridge
